//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiSinavProject.PL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deneme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deneme()
        {
            this.ServisDenemes = new HashSet<ServisDeneme>();
            this.SiparisDenemes = new HashSet<SiparisDeneme>();
            this.DenemeKullanicis = new HashSet<DenemeKullanici>();
            this.OturumDenemes = new HashSet<OturumDeneme>();
            this.Sorus = new HashSet<Soru>();
        }
    
        public int DenemeKey { get; set; }
        public int AlanKey { get; set; }
        public string Adi { get; set; }
        public int Sure { get; set; }
        public string Resim { get; set; }
        public string Link { get; set; }
        public decimal Fiyat { get; set; }
        public bool YeniMi { get; set; }
        public bool DemoMu { get; set; }
        public bool HediyeMi { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisDeneme> ServisDenemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDeneme> SiparisDenemes { get; set; }
        public virtual Alan Alan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenemeKullanici> DenemeKullanicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OturumDeneme> OturumDenemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soru> Sorus { get; set; }
    }
}
