//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiSinavProject.PL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenemeKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DenemeKullanici()
        {
            this.DenemeKullaniciSorus = new HashSet<DenemeKullaniciSoru>();
            this.SonucDetays = new HashSet<SonucDetay>();
        }
    
        public int DenemeKullaniciKey { get; set; }
        public int DenemeKey { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<int> AktifSoruKey { get; set; }
        public System.DateTime BaslangicZamani { get; set; }
        public System.DateTime BitisZamani { get; set; }
        public int GecenSure { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Deneme Deneme { get; set; }
        public virtual Soru Soru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenemeKullaniciSoru> DenemeKullaniciSorus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SonucDetay> SonucDetays { get; set; }
    }
}
