//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiSinavProject.PL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servi()
        {
            this.Dagitims = new HashSet<Dagitim>();
            this.ServisDenemes = new HashSet<ServisDeneme>();
            this.ServisEDergis = new HashSet<ServisEDergi>();
        }
    
        public int ServisKey { get; set; }
        public int SirketKey { get; set; }
        public int ServisTipKey { get; set; }
        public string Aciklama { get; set; }
        public string Kod { get; set; }
        public int Limit { get; set; }
        public System.DateTime Baslangic { get; set; }
        public System.DateTime Bitis { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dagitim> Dagitims { get; set; }
        public virtual ServisTip ServisTip { get; set; }
        public virtual Sirket Sirket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisDeneme> ServisDenemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisEDergi> ServisEDergis { get; set; }
    }
}
