//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiSinavProject.PL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sipari()
        {
            this.SiparisDenemes = new HashSet<SiparisDeneme>();
            this.SiparisEDergis = new HashSet<SiparisEDergi>();
        }
    
        public int SiparisKey { get; set; }
        public int SiparisDurumTipNo { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual SiparisDurumTip SiparisDurumTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDeneme> SiparisDenemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisEDergi> SiparisEDergis { get; set; }
    }
}
