//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiSinavProject.PL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soru()
        {
            this.DenemeKullanicis = new HashSet<DenemeKullanici>();
            this.DenemeKullaniciSorus = new HashSet<DenemeKullaniciSoru>();
        }
    
        public int SoruKey { get; set; }
        public int DersKey { get; set; }
        public Nullable<int> DenemeKey { get; set; }
        public Nullable<bool> SadeceDeneme { get; set; }
        public string DogruSik { get; set; }
        public byte SikSayisi { get; set; }
        public string Soru1 { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.Guid> KayitKisiKey { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<System.Guid> GuncelleKisiKey { get; set; }
        public Nullable<System.DateTime> GuncelleTarih { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Deneme Deneme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenemeKullanici> DenemeKullanicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenemeKullaniciSoru> DenemeKullaniciSorus { get; set; }
        public virtual Der Der { get; set; }
    }
}
